apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tu6d960cn-go 
  janus-idp.io/tekton: tu6d960cn-go
  backstage.io/kubernetes-id: tu6d960cn-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tu6d960cn-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml