apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tu6d960cn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tu6d960cn-go 
  name: tu6d960cn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tu6d960cn-go 
